server:
  port: 9004

spring:
  application:
    name: product-service

  # Import .env file
  config:
    import: optional:file:.env[.properties]

  # Database Settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # Timezone Setting
  jackson:
    time-zone: Asia/Seoul
